
CREATE TABLE CLIENTES(
        ID INTEGER NOT NULL,        
	FIRSTNAME VARCHAR(255),
        LASTNAME  VARCHAR(15),
        TELEFONO INTEGER,
        DIRECCION VARCHAR(255),
        PRIMARY KEY (ID)
);

CREATE TABLE DETALLE(
    
    DETALLE_ID INTEGER NOT NULL,  
    CANTIDAD INTEGER,
    DESCRIPCION VARCHAR(255),
    PRECIO INTEGER,    
    PRIMARY KEY (DETALLE_ID)

);

CREATE TABLE FACTURA (
    FACTURA_ID INTEGER NOT NULL, 
    FECHA VARCHAR(15),
    IVA INTEGER,
    PRIMARY KEY (FACTURA_ID)

);